import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Player from "../components/Player";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <video src="/video.mp4" className='backVideo' autoPlay muted/>
                <div className='info'>
                    <h1>😎Misha And Nikita Mood😎</h1>
                    <img src='/photo.jpg'/>
                    <Player url={'/audio.mp3'} />
                </div>
            </div>
        </div>
    )
}
