import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useState,useEffect} from "react";

const useAudio = url => {
    const [audio, setAudio] = useState(null);
    const [playing, setPlaying] = useState(false);
    useEffect(() => {
        setAudio(new Audio(url))
        playing ? audio?.play() : audio?.pause();
        // only run once on the first render on the client
    }, [playing])

    const toggle = () => setPlaying(!playing);

    useEffect(() => {
        audio?.addEventListener('ended', () => setPlaying(false));
        return () => {
            audio?.removeEventListener('ended', () => setPlaying(false));
        };
    }, []);

    return [playing, toggle];
};

export default function Home() {
    const [playing, toggle] = useAudio("/audio.mp3");
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <video src="/video.mp4" className='backVideo' autoPlay muted/>
                <div>
                    <h1>😎Misha And Nikita Mood😎</h1>
                    <button onClick={toggle}>Music</button>
                </div>
            </div>
        </div>
    )
}
